'use client';
import {useEffect,useRef} from 'react';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Database, MapPin, ShieldCheck, X } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Tooltip, CartesianGrid, Legend } from 'recharts';
import type { RiskRegion, Explanation, Mode } from '@/types';
import { color, fmt, INDICATORS } from './constants';
import TemperatureChart from './TemperatureChart';
import ReviewPanel from './ReviewPanel';
import RegionalWeather from './RegionalWeather';

type Props = {onWeather:(stationId?:string)=>void;onWeatherBack?:()=>void;mode:Mode; onFacilities:(code:string)=>void; cityDongs: boolean; region: RiskRegion | null; explanation: Explanation | null; tab: string; setTab: (tab: string) => void; loading: boolean; error: string | null; parent: string; sample: boolean; onDrill: (code: string) => void; onClose: () => void; onBusan: () => void};

export default function DataBoard({region: r, explanation, tab, setTab, loading, error, parent, sample, onDrill, onClose, onBusan, cityDongs, mode, onFacilities, onWeather, onWeatherBack}: Props) {
  const contentRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{contentRef.current?.scrollTo({top:0});},[tab,r?.region_code]);
  const weather = r?.factors.find(f => f.key === 'heatwave_intensity')?.source_detail;
  const currentWeatherAvailable = !sample && r?.region_code.startsWith('21') && r.region_code.length === 8;
  return <aside className="data-board" aria-label="지역 데이터보드">
    <div className="board-heading"><span><Activity size={17}/> 선택한 동네 분석</span><button className="icon-button" onClick={onClose} aria-label="지역 목록으로 돌아가기"><X size={17}/></button></div>
    {onWeatherBack&&<button className="analysis-weather-back" onClick={onWeatherBack}>← 기상 비교 지도로 돌아가기</button>}
    <div className="board-tabs" role="tablist" aria-label="분석 항목">{['위험현황', '현재기상', '원인분석', '대응방안', '보고서'].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)} className={tab === t ? 'active' : ''}>{t}</button>)}</div>
    <div className="board-content" aria-busy={loading} ref={contentRef}>
      {!r ? <div className="board-welcome"><div className="welcome-icon"><MapPin size={30} strokeWidth={1.4}/></div><span className="eyebrow">우리 지역을 이해하는 첫걸음</span><h2>{cityDongs ? <>순위나 지도에서<br/>동을 선택해 주세요.</> : <>지도에서 지역을<br/>선택해 주세요.</>}</h2><p>동별 인구와 주거환경을 함께 살펴보고,<br/>우선 대응이 필요한 이유를 확인하세요.</p><div className="welcome-steps"><span><b>01</b> 지역의 통계를 살펴보고</span><span><b>02</b> 주요 취약요인을 비교하고</span><span><b>03</b> 대응방안을 검토하세요</span></div><button className="primary-button" onClick={onBusan}>부산 전체 읍면동 보기 <ArrowRight size={16}/></button></div> : <>
        <div className="selected-region"><div><span className="eyebrow">{r.full_name.replace(r.region_name, '').trim() || '선택 지역'}</span><h2>{r.region_name}<span className="region-dot"/></h2></div><MapPin size={24} strokeWidth={1.3}/></div>
        {r.region_code.length < 8 && <button className="drill-button" onClick={() => onDrill(r.region_code)}>{r.region_code.length === 2 ? '시군구별' : '읍면동별'} 자세히 보기 <ArrowRight size={15}/></button>}
        {sample && <div className="sample-inline">시연용 합성 데이터 · 실제 위험도 아님</div>}
        {currentWeatherAvailable && (tab==='위험현황'||tab==='현재기상') && <RegionalWeather onMap={onWeather} key={r.region_code} code={r.region_code} detailed={tab==='현재기상'} onDetails={()=>setTab('현재기상')}/>}
        {tab==='현재기상'&&!currentWeatherAvailable&&<p className="section-caption">실제 공공데이터 모드에서 부산 읍·면·동을 선택하면 인근 관측소의 최근 기상을 확인할 수 있습니다.</p>}
        {tab==='위험현황'&&!sample && weather?.station_id && <details className="station-details"><summary>분석에 사용한 기상 관측정보</summary><div className="station-note"><strong>{r.reference_year}년 분석 관측소 · {weather.station_name} ({weather.station_id})</strong><span>대표 위치에서 {fmt(weather.distance_km ?? null, 2)}km · {r.reference_year}년 6~8월</span><p>인근 관측소 기준이며 해당 지역의 직접 실측값은 아닙니다. 폭염일수는 일 최고기온 33℃ 이상인 날의 수입니다.</p><small>유효 관측: 평균기온 {weather.valid_mean_days}/{weather.expected_days}일 · 최고기온 {weather.valid_max_days}/{weather.expected_days}일</small></div></details>}
        {error && <div className="inline-error" role="alert">{error}</div>}
        {loading && <div className="detail-loading">상세 통계를 불러오고 있습니다…</div>}
        {tab === '위험현황' && <>
          
          <section className="score-card">{cityDongs && <p className="priority-context">부산 전체 읍면동 비교 · 대응 우선순위 검토용</p>}<div className="section-title"><h3>폭염 취약도</h3><span title="현재 비교지역 안에서 정규화한 상대 지수이며 재난 발생확률이 아닙니다."><CircleHelp size={14}/></span></div>
            <div className="score-visual"><svg viewBox="0 0 160 160" aria-hidden="true"><circle cx="80" cy="80" r="66" fill="none" stroke="#e9efeb" strokeWidth="9"/><circle cx="80" cy="80" r="66" fill="none" stroke={color(r.risk_score)} strokeWidth="9" strokeLinecap="round" strokeDasharray={`${(r.risk_score || 0) * 4.147} 415`} transform="rotate(-90 80 80)"/></svg><div><strong>{fmt(r.risk_score)}</strong><span>{r.risk_score == null ? '종합점수 미산출' : '/ 100'}</span></div></div>
            <span className="risk-badge" style={{color: r.risk_score == null ? '#687970' : color(r.risk_score)}}>{r.risk_level}</span>
            <p>{r.risk_score == null ? '필수 지표가 모두 확보되면 계산합니다.' : `${r.comparison_region} 내 상대적 폭염 취약성`}</p>
            {r.no_variation && <p className="notice-text">비교지역 간 계산 결과의 차이가 없습니다.</p>}
          </section>
          <div className="average-strip"><span>{r.comparison_region} 점수 평균</span><strong>{fmt(r.comparison_risk_average)}</strong><span className="difference">{r.risk_difference == null ? '비교 불가' : `${r.risk_difference >= 0 ? '+' : ''}${fmt(r.risk_difference)}점`}</span></div>
          <section className="board-section"><div className="section-title"><h3>분석 데이터 확보율</h3><b>{Math.round(r.data_completeness * 100)}<small>%</small></b></div><div className="progress-track"><i style={{width: `${r.data_completeness * 100}%`}}/></div><div className="availability-list">{r.factors.map(f => <div key={f.key}><span>{f.name}</span>{f.value == null ? <span className="unavailable" title={f.source_detail?.reason || '미확보'}>미확보</span> : <span className="available"><Check size={12}/> {fmt(f.value, f.unit === '명' ? 0 : 1)}{f.unit}</span>}</div>)}</div></section>
          <details className="historical-weather"><summary>취약도 분석에 사용한 여름 기온</summary><TemperatureChart key={`${mode}-${r.region_code}`} code={r.region_code} mode={mode}/></details><div className="info-note"><ShieldCheck size={16}/><p>없는 값을 평균이나 0으로 채우지 않습니다. 이 점수는 재난 발생확률이 아닙니다.</p></div>
        </>}
        {tab === '원인분석' && <>
          <section className="board-section"><div className="section-title"><h3>주요 위험요인</h3><span className="muted">TOP 3</span></div><p className="section-caption">{r.risk_score == null ? '확보된 지표의 상대 기여도입니다. 종합 위험원인으로 단정하지 않습니다.' : '정규화 값 × 해당 지표의 가중치'}</p><div className="factor-cards">{r.top_factors.map((f, i) => <div className="factor-card" key={f.key}><span className="factor-index">0{i + 1}</span><div><h4>{f.name}</h4><p>{f.comparison_region} 기준 {fmt(f.comparison_average)}{f.unit}</p></div><strong>{fmt(f.value, f.unit === '명' ? 0 : 1)}<small>{f.unit}</small></strong></div>)}{!r.top_factors.length && <p className="section-caption">이 지역은 현재 실제 분석 범위에 포함되지 않습니다.</p>}</div></section>
          <section className="board-section"><h3>위험도 구성요소</h3><div className="hev-bars">{[{key: 'hazard_score', name: 'Hazard', label: '폭염 강도'}, {key: 'exposure_score', name: 'Exposure', label: '인구 노출'}, {key: 'vulnerability_score', name: 'Vulnerability', label: '사회적 취약성'}].map(group => {const value = r[group.key as 'hazard_score']; return <div key={group.key}><div><span><b>{group.name}</b> {group.label}</span><strong>{fmt(value)}</strong></div><div className="progress-track"><i style={{width: `${value || 0}%`}}/></div></div>;})}</div></section>
          <section className="board-section"><h3>지표별 상대 기여도</h3><div className="contribution-chart"><ResponsiveContainer width="100%" height={155}><BarChart data={r.top_factors.map(f => ({name: f.name.replace('65세 이상 인구 비율', '고령인구').replace('1인가구 비율', '1인가구').replace('30년 이상 노후주택 비율', '노후주택'), contribution: Number((f.contribution || 0).toFixed(3))}))} layout="vertical" margin={{left: 0, right: 14}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e9ece8"/><XAxis type="number" domain={[0, 1]} tick={{fontSize: 10}} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={62} tick={{fontSize: 11}} axisLine={false} tickLine={false}/><Tooltip formatter={v => [v, '기여도']}/><Bar isAnimationActive={false} dataKey="contribution" fill="#458773" radius={[0, 4, 4, 0]} barSize={16}/></BarChart></ResponsiveContainer></div></section>
          <section className="board-section"><h3>지역 평균과 비교</h3><p className="section-caption">고령·1인가구: 합산 비율 / 노후주택: 공식 지역 비율 · 차이 %p</p><div className="average-chart" aria-label="선택지역과 상위지역의 비율 비교 차트"><ResponsiveContainer width="100%" height={195}><BarChart data={r.factors.filter(f => f.unit === '%').map(f => ({name: f.key === 'elderly_ratio' ? '고령인구' : f.key === 'single_household_ratio' ? '1인가구' : '노후주택', selected: f.value, average: f.comparison_average}))} margin={{left: -22, right: 0, top: 15}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e9ece8"/><XAxis dataKey="name" tick={{fontSize: 10}} axisLine={false} tickLine={false}/><YAxis domain={[0, 100]} tick={{fontSize: 9}} axisLine={false} tickLine={false} unit="%"/><Tooltip formatter={(v, name) => [fmt(v as number) + '%', name]}/><Legend wrapperStyle={{fontSize: 9}} iconType="square" iconSize={7}/><Bar isAnimationActive={false} dataKey="selected" name={r.region_name} fill="#458773" radius={[3, 3, 0, 0]} barSize={17}/><Bar isAnimationActive={false} dataKey="average" name={r.comparison_region} fill="#c8d6b7" radius={[3, 3, 0, 0]} barSize={17}/></BarChart></ResponsiveContainer></div><div className="comparison-table"><div className="comparison-head"><span>취약성 지표</span><span>선택지역</span><span>{r.comparison_region}</span></div>{r.factors.filter(f => f.unit === '%').map(f => <div key={f.key}><span>{f.name.replace('65세 이상 인구 비율', '고령인구').replace('1인가구 비율', '1인가구').replace('30년 이상 노후주택 비율', '노후주택')}<small className={(f.difference_pp || 0) > 0 ? 'up' : 'down'}>{f.difference_pp == null ? '비교 불가' : <>{f.difference_pp > 0 ? <ArrowUpRight size={11}/> : <ArrowDownRight size={11}/>} {fmt(Math.abs(f.difference_pp))}%p</>}</small></span><b>{fmt(f.value)}{f.value != null && '%'}</b><span>{fmt(f.comparison_average)}{f.comparison_average != null && '%'}</span></div>)}</div>
            {parent.length === 5 && r.busan_comparison && <div className="busan-comparison"><h4>부산광역시 전체와 비교</h4>{r.busan_comparison.filter(f => f.unit === '%').map(f => <div key={f.key}><span>{INDICATORS.find(i => i.key === f.key)?.name}</span><b>{fmt(f.comparison_average)}%</b></div>)}</div>}
          </section>
        </>}
        {tab === '대응방안' && (r.region_code.length===8&&r.region_code.startsWith('21') ? <ReviewPanel key={`${mode}-${r.region_code}`} code={r.region_code} mode={mode} onFacilities={onFacilities} variant="actions" onReport={()=>setTab('보고서')}/> : <>
          
          {explanation ? <><section className="explanation-card"><h3>지역 분석 요약</h3><p>{explanation.summary}</p></section><section className="board-section"><h3>통계가 보여주는 특성</h3>{explanation.causes.map(c => <p className="cause-text" key={c.factor_key}>{c.text}</p>)}</section><section className="board-section"><div className="section-title"><h3>우선 검토할 대응방안</h3><ShieldCheck size={17}/></div><div className="action-cards">{explanation.actions.map((a, i) => <div className="action-card" key={a.title}><span>{String(i + 1).padStart(2, '0')}</span><div><small>{a.factor_name}</small><h4>{a.title}</h4><p>지역 여건과 대상자 현황을 확인한 후 검토할 수 있습니다.</p></div></div>)}{!explanation.actions.length && <p className="section-caption">확보된 위험요인에 연결할 수 있는 대응방안이 없습니다. 추가 데이터 확인이 필요합니다.</p>}</div></section><div className="info-note"><CircleHelp size={16}/><p>{explanation.disclaimer}</p></div></> : <p className="section-caption">{loading ? '분석 결과를 문장으로 정리하고 있습니다…' : '지역을 선택하면 계산된 통계를 바탕으로 설명합니다.'}</p>}
        </>)}
        {tab === '보고서' && (r.region_code.length === 8 && r.region_code.startsWith('21') ? <ReviewPanel key={`${mode}-${r.region_code}`} code={r.region_code} mode={mode} onFacilities={onFacilities}/> : <p className="section-caption">부산의 읍·면·동을 선택하면 지역 분석보고서를 확인할 수 있습니다.</p>)}
        
      </>}
    </div>
  </aside>;
}
