'use client';
import {MapPin, Umbrella, Building2, Search, X} from 'lucide-react';
import {useState} from 'react';
import type {Facility, FacilityData, FacilityFilters} from '@/types';

type Props={data:FacilityData|null; error:string|null; region:string; kind:string; rows:Facility[]; selected:Facility|null; onRegion:(code:string)=>void; onKind:(kind:string)=>void; onSelect:(row:Facility|null)=>void; onRetry:()=>void;filters:FacilityFilters;onFilters:(v:FacilityFilters)=>void};
export default function FacilityPanel({data,error,region,kind,rows,selected,onRegion,onKind,onSelect,onRetry,filters,onFilters}:Props){
 const [query,setQuery]=useState('');
 const filtered=rows.filter(r=>(r.name+' '+r.address).includes(query.trim()));
 const district=region.length>=5?region.slice(0,5):'';
 return <aside className="facility-panel" aria-label="현재 시설 목록">
  <div className="facility-heading"><span className="eyebrow">FACILITIES · 2026</span><h1>지금 우리 동네의<br/>쉼터와 그늘막</h1><p>공식 자료에 등록된 시설 위치를 살펴보세요.</p><div className="facility-year-note">2026년 시설 현황 · 취약성 분석과 별도 화면</div></div>
  {error?<div role="alert" className="facility-error"><p>{error}</p><button onClick={onRetry}>다시 불러오기</button></div>:!data?<p className="facility-loading">시설자료를 불러오고 있습니다…</p>:<>
  <div className="facility-filters"><div className="region-selectors"><label><span>구·군</span><select aria-label="시설 구·군" value={district} onChange={e=>{onRegion(e.target.value||'21');setQuery('');}}><option value="">부산 전체</option>{data.regions.filter(r=>r.region_level==='sigungu').map(r=><option key={r.region_code} value={r.region_code}>{r.region_name}</option>)}</select></label><label><span>읍면동</span><select aria-label="시설 읍면동" value={region.length===8?region:''} disabled={!district} onChange={e=>onRegion(e.target.value||district)}><option value="">전체 읍면동</option>{data.regions.filter(r=>r.parent_region_code===district).map(r=><option key={r.region_code} value={r.region_code}>{r.region_name}</option>)}</select></label></div>
   <div className="facility-kind" role="group" aria-label="시설 유형">{[{key:'all',label:'전체'},{key:'shelter',label:'무더위쉼터'},{key:'shade',label:'그늘막'}].map(k=><button key={k.key} aria-pressed={kind===k.key} onClick={()=>onKind(k.key)}>{k.label}</button>)}</div>
   {kind!=='shade'&&<div className="shelter-options"><label>쉼터 이용대상<select aria-label="쉼터 이용대상" value={filters.access} onChange={e=>onFilters({...filters,access:e.target.value})}><option value="all">전체 · 특정인 이용시설 포함</option><option value="anyone">누구나 이용 가능한 쉼터</option></select></label><div className="schedule-inputs"><label>등록 운영요일<select aria-label="쉼터 운영요일" value={filters.day} onChange={e=>onFilters({...filters,day:e.target.value,time:e.target.value===''?'':filters.time})}><option value="">요일 무관</option>{['월','화','수','목','금','토','일'].map((d,i)=><option key={d} value={i}>{d}요일</option>)}</select></label><label>등록 운영시간<input type="time" aria-label="쉼터 운영시간" disabled={filters.day===''} value={filters.time} onChange={e=>onFilters({...filters,time:e.target.value})}/></label></div><p>등록된 일반 운영일 기준입니다. 공휴일·폭염특보 연장 운영과 실시간 개방 여부는 반영하지 않습니다.</p></div>}
   <label className="facility-search"><Search size={15}/><input aria-label="시설명 또는 주소 검색" placeholder="시설명 또는 주소 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  </div>
  {selected&&<section className="facility-detail"><button className="icon-button" aria-label="시설 상세 닫기" onClick={()=>onSelect(null)}><X size={16}/></button><span className={`facility-tag ${selected.kind}`}>{selected.kind==='shelter'?'무더위쉼터':'그늘막'}</span><h2>{selected.name}</h2><p><MapPin size={13}/>{selected.address}</p><dl><dt>자료 기준</dt><dd>{selected.reference_date}</dd>{selected.kind==='shelter'?<><dt>이용대상</dt><dd>{selected.access}</dd>{selected.filter_status==='unknown'&&<><dt>필터 판정</dt><dd>운영·이용조건 확인 필요</dd></>}<dt>등록 운영시간</dt><dd>{selected.hours}</dd><dt>등록 수용인원</dt><dd>{selected.capacity==null?'미제공':`${selected.capacity}명`}</dd></>:<><dt>설치일</dt><dd>{selected.installed_at||'미제공'}</dd></>}<dt>좌표 기준 행정동</dt><dd>{selected.region_name||'경계 연결 미확인'}</dd></dl><a href={selected.source_url} target="_blank" rel="noreferrer">{selected.source} ↗</a><small>실시간 개방 여부가 아닙니다. 방문 전 운영정보를 확인하세요.</small></section>}
  <div className="facility-list-heading"><strong>{filtered.length.toLocaleString()}개 등록 위치</strong><span>지도와 목록에서 선택</span></div>
  {kind!=='shade'&&<p className="facility-match-count">쉼터 조건 일치 {rows.filter(r=>r.kind==='shelter'&&r.filter_status!=='unknown').length}개 · 조건 확인 필요 {rows.filter(r=>r.filter_status==='unknown').length}개</p>}
  <div className="facility-list">{filtered.slice(0,100).map(r=><button key={r.id} className={selected?.id===r.id?'active':''} onClick={()=>onSelect(r)}><span className={`facility-icon ${r.kind}`}>{r.kind==='shelter'?<Building2 size={17}/>:<Umbrella size={17}/>}</span><span><strong>{r.name}</strong><small>{r.address}</small><em>{r.kind==='shelter'?`무더위쉼터 · ${r.access}${r.filter_status==='unknown'?' · 조건 확인 필요':''}`:'그늘막'}</em></span></button>)}{filtered.length>100&&<p className="facility-more">목록은 100개까지 표시합니다. 지역이나 검색어로 좁혀 주세요. 지도에는 선택한 지역·유형의 모든 등록시설을 표시합니다.</p>}{!filtered.length&&<p className="facility-more">현재 필터에 맞는 등록자료가 없습니다. 시설이 없다는 판정은 아닙니다.</p>}</div>
  <div className="facility-footnote"><p>쉼터: 국민안전24 2026년 등록자료<br/>그늘막: 부산생활지도 2026.04.30 기준</p><p>좌표 미확인 {data.meta.excluded_coordinate_count}건은 지도에서 제외했습니다. 행정동 연결 미확인 {data.meta.unassigned_region_count}건은 부산 전체에서 확인할 수 있습니다.</p><p>지역은 시설의 등록 위치를 기준으로 구분합니다. 원본 주소의 지역과 다를 수 있습니다.</p><p>시설 개수는 부족 여부나 확충 우선순위를 뜻하지 않습니다.</p></div>
  </>}
 </aside>;
}
