'use client';
import {ArrowLeft,ArrowRight,ClipboardCheck,Download,MapPin,Trash2} from 'lucide-react';
import type {useInspectionList} from '@/hooks/useInspectionList';
import type {InspectionItem} from './inspection';
import {inspectionMarkdown} from './inspection';
type Props={list:ReturnType<typeof useInspectionList>;onOpen:(item:InspectionItem)=>void;onClose:()=>void;onFind:()=>void};
export default function InspectionList({list,onOpen,onClose,onFind}:Props){
 const save=()=>{const url=URL.createObjectURL(new Blob([inspectionMarkdown(list.items)],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='기후대비_점검목록.md';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="inspection-list" aria-label="나의 점검 목록"><button className="inspection-back" onClick={onClose}><ArrowLeft size={15}/>지도 탐색으로 돌아가기</button><div className="inspection-intro"><ClipboardCheck size={26}/><h1>나의 점검 목록</h1><p>살펴볼 동네와 시설을 모아두고,<br/>현장에서 확인한 내용을 남겨보세요.</p></div><div className="inspection-summary"><span>담은 곳 <strong>{list.items.length}</strong></span><span>점검 완료 <strong>{list.items.filter(item=>item.checked).length}</strong></span><button disabled={!list.items.length} onClick={save}><Download size={15}/>내려받기</button></div><p className="inspection-storage">{list.error?'목록을 파일로 내려받아 보관할 수 있습니다.':'이 브라우저에 자동 저장됩니다.'}</p>{list.error&&<p role="alert">{list.error}</p>}
  {!list.items.length?<div className="inspection-empty"><MapPin size={27}/><h2>아직 담은 곳이 없어요</h2><p>동네 찾기 결과나 재해 지점·시설 상세에서<br/>‘점검 목록에 담기’를 눌러보세요.</p><button className="primary-button" onClick={onFind}>살펴볼 동네 찾기<ArrowRight size={15}/></button></div>:<div className="inspection-cards">{list.items.map(item=><article key={item.id} data-id={item.id}><div className="inspection-card-heading"><span>{({region:'동네',facility:'시설',flood:'침수 기록',landslide:'산사태 지정 지점'})[item.kind]}</span><button aria-label={`${item.title} 목록에서 빼기`} onClick={()=>list.remove(item.id)}><Trash2 size={15}/></button></div><h2>{item.title}</h2><p>{item.regionName}</p><small>{item.reference}</small><ul>{item.evidence.map((line,i)=><li key={i}>{line}</li>)}</ul><label className="inspection-check"><input type="checkbox" checked={item.checked} onChange={e=>list.update(item.id,{checked:e.target.checked})}/>현장 점검 완료</label><label className="inspection-note">확인할 내용·현장 메모<textarea aria-label={`${item.title} 점검 메모`} rows={2} maxLength={2000} value={item.note} onChange={e=>list.update(item.id,{note:e.target.value})} placeholder="운영시간, 이용대상, 현장 확인할 사항 등"/></label><div className="inspection-card-actions"><a href={item.sourceUrl} target="_blank" rel="noreferrer">자료 출처</a><button onClick={()=>onOpen(item)}>지도에서 다시 보기<ArrowRight size={14}/></button></div></article>)}</div>}
 </section>;
}
