import {chooseNavigation,selectAnalysisTab} from './navigation.mjs';
import {chromium, expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
if(process.argv.includes('--weather-links')){await import('./weather-links.mjs');process.exit(0);}
if(process.argv.includes('--flood-only')){await import('./flood.mjs');process.exit(0);}
if(process.argv.includes('--reports-only')){await import('./reports.mjs');process.exit(0);}
const root=path.resolve(import.meta.dirname,'../..');
fs.mkdirSync(path.join(root,'var/regression-screenshots'),{recursive:true});
const weatherSnapshot=JSON.parse(fs.readFileSync(path.join(root,'data/processed/current_weather_2026.json'),'utf8'));
const busanLatestDate=weatherSnapshot.stations.find(s=>s.station_id==='159').latest.date;
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
// Automated camera tests must not scrape the community tile service.
let tileRequests=0;
await page.route('https://tile.openstreetmap.org/**', async route=>{tileRequests++;await route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGP4DwQACfsD/fteaysAAAAASUVORK5CYII=','base64')});});
// Refresh job protocol is isolated so UI regressions never start an external collection.
await page.route('**/api/current-weather/refresh',route=>route.fulfill({json:{state:'fresh',message:'저장된 관측자료를 확인했습니다.'}}));
const shot=async name=>{await expect(page.locator('.detail-loading')).toHaveCount(0);await expect(page.locator('.updating-pill')).toHaveCount(0);await expect(page.locator('.map-canvas')).toHaveAttribute('data-ready','true');await page.waitForTimeout(750);await page.screenshot({path:path.join(root,'var/regression-screenshots',name+'.png'),fullPage:true});};
const explore=()=>chooseNavigation(page,'지역 탐색');
try {
 await page.goto(process.env.APP_URL||'http://127.0.0.1:3018');
 await expect(page.locator('.map-statusbar')).toContainText('206개 지역',{timeout:30000});
 await expect(page.locator('.map-statusbar')).toContainText('173개 종합점수',{timeout:30000});
 await expect(page.locator('.readiness-finder')).toBeVisible();
 await explore();
 await expect(page.locator('.ranking-list button')).toHaveCount(5);
 await expect(page.locator('.rank-district').first()).not.toBeEmpty();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-ready','true',{timeout:30000});
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','sigungu');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-feature-count','16');
 await expect(page.locator('.map-region-label[data-level="dong"]')).toHaveCount(0);
 const initialRanking=await page.locator('.ranking-list').innerText();
 await shot('27-zoomed-out-district-boundaries');
 await page.getByRole('button',{name:'지도 확대',exact:true}).click();await page.waitForTimeout(300);
 await page.getByRole('button',{name:'지도 확대',exact:true}).click();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','dong');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-feature-count','206');
 expect(await page.locator('.ranking-list').innerText()).toBe(initialRanking);
 await shot('28-zoomed-in-dong-boundaries');
 await page.getByRole('button',{name:'지도 축소',exact:true}).click();await page.waitForTimeout(300);
 await page.getByRole('button',{name:'지도 축소',exact:true}).click();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','sigungu');
 await shot('19-busan-dong-priority-left');
 await expect(page.locator('.map-title-card')).not.toContainText('2024');
 await expect(page.locator('.map-title-card')).not.toContainText('2025');
 await chooseNavigation(page,'침수');
 await expect(page.locator('.flood-count strong')).toHaveText('186건');
 await expect(page.locator('.score-card')).toHaveCount(0);
 await expect(page.locator('.map-legend')).toHaveCount(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await page.locator('.flood-record-list>button').first().click();
 await expect(page.locator('.flood-record-detail')).toContainText('현 지표에서 약 20cm~50cm');
 await expect(page.locator('.flood-record-detail')).toContainText('2020.07.22');
 await shot('40-flood-history-record');
 await page.getByLabel('침수 발생 연도',{exact:true}).selectOption('2025');
 await expect(page.locator('.flood-record-detail')).toHaveCount(0);
 await expect(page.locator('.flood-count strong')).toHaveText('8건');
 const floodSearch=page.getByRole('combobox',{name:'동네 이름 검색'});
 await floodSearch.fill('부곡4동');await floodSearch.press('ArrowDown');await floodSearch.press('Enter');
 await expect(page.getByLabel('침수 읍·면·동',{exact:true})).toHaveValue('21110600');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','dong');
 await page.getByRole('tab',{name:'침수 예상도',exact:true}).click();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-flood-layer','forecast');
 await expect(page.locator('.flood-record-list')).toHaveCount(0);
 await page.getByRole('button',{name:'지도 초기화',exact:true}).click();
 await page.getByRole('button',{name:'118.5mm/h 100년 빈도'}).click();
 await expect(page.locator('.map-title-card')).toContainText('118.5');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-flood-layer','forecast');
 await expect(page.locator('.flood-reading')).toContainText('지금 침수된');
 await shot('41-flood-scenario-100');
 await page.getByLabel('침수 구·군',{exact:true}).selectOption('21060');
 await expect(page.getByLabel('침수 구·군',{exact:true})).toHaveValue('21060');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','dong');
 await shot('42-flood-neighborhood-forecast');
 await page.getByRole('tab',{name:'과거 침수 이력',exact:true}).click();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-flood-layer','history');
 await chooseNavigation(page,'폭염');
 await expect(page.locator('main')).toHaveAttribute('data-region','21060');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).fill('부곡4동');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).press('Enter');
 await expect(page.locator('.selected-region')).toContainText('부곡4동');
 await expect(page.locator('.score-visual strong')).toHaveText('100.0');
 await expect(page.locator('.data-board')).not.toContainText('규칙 기반');
 await explore();

 await chooseNavigation(page,'현재 시설');
 await expect(page.getByLabel('시설 읍면동',{exact:true})).toHaveValue('21110600');
 await page.getByLabel('시설 구·군',{exact:true}).selectOption('');
 await expect(page.locator('.map-statusbar')).toContainText('3,569개 시설');
 await expect(page.locator('.map-title-card')).not.toContainText('2024');
 await expect(page.locator('.map-title-card')).not.toContainText('취약성');
 await expect(page.locator('.sidebar')).toBeHidden();
 await expect(page.locator('.data-board')).toBeHidden();
 await expect(page.locator('.map-legend')).toHaveCount(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await shot('24-current-facilities-separate');
 await page.getByLabel('시설 구·군',{exact:true}).selectOption('21090');
 await page.getByRole('button',{name:'무더위쉼터',exact:true}).click();
 // Spatial membership uses source coordinates, which can differ from source district registration.
 await expect(page.locator('.facility-list-heading')).toContainText('107개');
 await page.locator('.facility-list>button').first().click();
 await expect(page.locator('.facility-detail')).toContainText('2026년 등록자료');
 await expect(page.locator('.facility-detail')).toContainText('등록 운영시간');
 await shot('25-current-shelter-detail');
 await page.getByRole('button',{name:'시설 상세 닫기',exact:true}).click();
 const canvas=await page.locator('.map-canvas').boundingBox();
 await page.mouse.click(canvas.x+canvas.width/2,canvas.y+canvas.height/2);
 await expect(page.locator('.facility-detail')).toBeVisible();
 await page.getByRole('button',{name:'그늘막',exact:true}).click();
 await page.locator('.facility-list>button').first().click();
 await expect(page.locator('.facility-detail')).toContainText('2026-04-30');
 await expect(page.locator('.facility-detail')).toContainText('설치일');
 await shot('26-current-shade-detail');
 await page.locator('.app-header').getByRole('button',{name:'데이터 안내'}).click();
 await expect(page.getByRole('dialog')).toContainText('국민안전24');
 await expect(page.getByRole('dialog')).not.toContainText('2024');
 await page.keyboard.press('Escape');
 await explore();
 await expect(page.locator('.facility-panel')).toHaveCount(0);
 await expect(page.locator('.map-legend')).toBeVisible();

 await page.locator('.ranking-list button').first().click();
 await expect(page.locator('.score-visual strong')).toHaveText('100.0');
 await expect(page.locator('.priority-context')).toContainText('부산 전체 읍면동');
 const panel=await page.locator('.data-board').boundingBox(), map=await page.locator('.map-section').boundingBox();
 expect(panel.x).toBeLessThan(map.x+map.width/2);
 expect(panel.x+panel.width).toBeLessThanOrEqual(map.x+map.width);
 await expect(page.locator('.station-note')).toContainText('인근 관측소');
 const analysisWeather=await (await page.request.get(new URL('/api/weather/21110600?mode=sgis',page.url()).href)).json();
 await expect(page.locator('.heat-period-summary .maximum strong')).toHaveText(`${analysisWeather.summary.maximum.value.toFixed(1)}℃`);
 await expect(page.locator('.heat-period-summary .minimum strong')).toHaveText(`${analysisWeather.summary.minimum.value.toFixed(1)}℃`);
 await expect(page.locator('.heat-period-summary .heat-period-range')).toHaveText(analysisWeather.period.join(' ~ '));
 await expect(page.locator('.heat-period-summary .heatwave-days strong')).toHaveText(`${analysisWeather.heatwave_days}일`);
 await expect(page.locator('.heat-period-summary .maximum>small')).toHaveText(analysisWeather.summary.maximum.dates.join(', '));
 await expect(page.locator('.regional-latest')).toHaveCount(0);
 await shot('37-neighborhood-period-temperature-summary');
 await page.setViewportSize({width:375,height:900});
 await expect(page.locator('.heat-period-summary .maximum strong')).toBeInViewport();
 await expect(page.locator('.heat-period-summary .minimum strong')).toBeInViewport();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(375);
 await shot('37-period-temperature-mobile');
 await page.setViewportSize({width:1440,height:1000});
 const regionWeather=await (await page.request.get(new URL('/api/current-weather/regions/21110600',page.url()).href)).json();
 await page.getByRole('button',{name:'최근 기온·올여름 기록 보기',exact:true}).click();
 await expect(page.getByRole('tab',{name:'현재기상',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await expect(page.locator('.regional-weather.expanded')).toContainText(regionWeather.station.station_name+' 관측소');
 await expect(page.locator('.regional-observed-date')).toContainText(regionWeather.station.latest.date);
 await expect(page.locator('.regional-weather-chart')).toBeVisible();
 await expect(page.locator('.station-note')).toHaveCount(0);
 await expect(page.locator('.board-source')).toHaveCount(0);
 await shot('38-neighborhood-current-weather-detail');
 await page.getByRole('button',{name:'올여름 · 6~8월',exact:true}).click();
 await expect(page.locator('.regional-weather .weather-period')).toContainText('2026-06-01');
 await expect(page.locator('.regional-weather .maximum strong')).toContainText(String(regionWeather.station.summer.summary.maximum.value));
 await selectAnalysisTab(page,'위험현황');

 await page.locator('.historical-weather>summary').click();
 await expect(page.locator('.temperature-loading')).toHaveCount(0);
 await expect(page.locator('.historical-weather .temperature-extremes .maximum strong')).toContainText('℃');
 await expect(page.locator('.historical-weather .temperature-extremes .maximum strong')).not.toContainText('—');
 await expect(page.locator('.temperature-chart')).toBeVisible();
 await shot('29-daily-maximum-minimum-temperature');
 await shot('20-left-dong-analysis');
 await selectAnalysisTab(page,'원인분석');
 await expect(page.locator('.factor-card')).toHaveCount(3);
 await shot('21-left-dong-factors');
 await selectAnalysisTab(page,'대응방안');
 await expect(page.locator('.response-panel')).toContainText('우선 검토할 대응방안');
 await expect(page.locator('.response-plan')).toHaveCount(3);
 await shot('22-left-dong-actions');
 await selectAnalysisTab(page,'보고서');
 await expect(page.locator('.review-rank')).toContainText('1위');
 await expect(page.locator('.review-rank')).toContainText('173개');
 await shot('36-automatic-regional-report');
 await expect(page.locator('.review-panel input, .review-panel textarea')).toHaveCount(0);
 await expect(page.locator('.report-focus')).toContainText('먼저 할 일');
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'보고서 저장 (.md)',exact:true}).click();
 const download=await downloadPromise;await download.saveAs(path.join(root,'var/review-download.md'));
 const report=fs.readFileSync(path.join(root,'var/review-download.md'),'utf8');
 expect(report).toContain('부곡4동 지역 분석보고서');expect(report).toContain('173개 산출 지역 중 1위');expect(report).not.toContain('검토 메모');expect(report).toContain('현장 확인 사항');expect(report).toContain('2026년 현재 시설은 별도 화면');
 await page.getByRole('button',{name:'이 동의 현재 시설 확인',exact:true}).click();
 await expect(page.locator('.facility-panel')).toBeVisible();
 await expect(page.getByLabel('시설 읍면동',{exact:true})).not.toHaveValue('');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','dong');
 await expect(page.locator('.map-legend')).toHaveCount(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await shot('31-review-to-current-facilities');
 await page.getByRole('button',{name:'무더위쉼터',exact:true}).click();
 await page.getByLabel('쉼터 이용대상',{exact:true}).selectOption('anyone');
 await expect(page.locator('.facility-list-heading')).toContainText('3개');
 await page.getByLabel('쉼터 이용대상',{exact:true}).selectOption('all');
 await page.getByLabel('쉼터 운영요일',{exact:true}).selectOption('0');
 await page.getByLabel('쉼터 운영시간',{exact:true}).fill('14:00');
 await expect(page.locator('.facility-match-count')).toContainText('조건 확인 필요');
 await shot('39-current-facilities-without-walking-overlay');

 await page.getByRole('button',{name:'선택한 동의 보고서로 돌아가기',exact:false}).click();
 await expect(page.locator('.review-rank')).toContainText('1위');
 await expect(page.locator('.review-panel input, .review-panel textarea')).toHaveCount(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await expect.poll(()=>tileRequests).toBeGreaterThan(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await page.getByRole('button',{name:'지도 확대',exact:true}).click();
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await page.getByRole('button',{name:'상세 패널 닫기'}).click();
 await expect(page.locator('.left-workspace')).toBeHidden();
 await explore();
 await page.getByRole('button',{name:'구·군 요약',exact:true}).click();
 await expect(page.locator('.map-statusbar')).toContainText('16개 지역');
 await page.getByRole('button',{name:'해운대구 지도에서 선택',exact:true}).click();
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-display-level','dong');
 await page.getByRole('button',{name:'읍면동별 자세히 보기'}).click();
 await page.getByRole('button',{name:'우1동 지도에서 선택',exact:true}).click();
 await selectAnalysisTab(page,'원인분석');
 await expect(page.locator('.busan-comparison')).toBeVisible();
 await selectAnalysisTab(page,'현재기상');
 await expect(page.locator('.regional-weather')).not.toHaveAttribute('data-region','21110600');
 await expect(page.locator('.regional-station')).toContainText('해운대 관측소');
 await expect(page.locator('.regional-weather-chart')).toBeVisible();

 await explore();
 await page.getByLabel('시·군·구',{exact:true}).selectOption('21110');
 await page.getByRole('button',{name:'선두구동 지도에서 선택',exact:true}).click();
 await selectAnalysisTab(page,'위험현황');
 await expect(page.locator('.score-visual strong')).toHaveText('—');
 await expect(page.locator('.station-note')).toContainText('88/92일');
 await expect(page.locator('.heat-period-summary .maximum')).toContainText('기간값 미산출');
 await expect(page.locator('.heat-period-summary .minimum')).toContainText('기간값 미산출');
 await expect(page.locator('.heat-period-summary .maximum strong')).toHaveText('—℃');
 if(!await page.locator('.historical-weather').getAttribute('open').then(v=>v!==null))await page.locator('.historical-weather>summary').click();
 await expect(page.locator('.historical-weather .temperature-extremes .maximum')).toContainText('기간값 미산출');
 await expect(page.locator('.historical-weather .temperature-extremes .minimum')).toContainText('기간값 미산출');
 await shot('23-left-missing-data');
 await chooseNavigation(page,'기상 비교');
 await expect(page.locator('.current-weather-panel')).toBeVisible();
 await page.getByLabel('기상 관측소',{exact:true}).selectOption('159');
 await expect(page.locator('.map-section')).toBeVisible();
 await expect(page.locator('.weather-latest')).toContainText(busanLatestDate);
 await expect(page.locator('.current-weather-chart')).toBeVisible();
 await expect(page.locator('.weather-map')).toHaveAttribute('data-ready','true');
 await page.waitForTimeout(750);
 await page.screenshot({path:path.join(root,'var/regression-screenshots/34-current-weather-recent.png'),fullPage:true});
 await page.getByRole('button',{name:'여름 기록 · 6~8월',exact:true}).click();
 await expect(page.locator('.current-weather-panel .maximum strong')).toContainText('38.8');
 await page.locator('.current-weather-panel').evaluate(el=>el.scrollTop=280);
 await page.waitForTimeout(400);
 await page.screenshot({path:path.join(root,'var/regression-screenshots/35-current-weather-summer.png'),fullPage:true});
 await page.getByLabel('기상 관측소',{exact:true}).selectOption('968');
 await expect(page.locator('.weather-latest')).toContainText('미확인');
 await page.getByLabel('기상 관측소',{exact:true}).selectOption('159');
 await page.locator('.weather-refresh-details summary').click();
 await page.getByRole('button',{name:'기상청 자료 갱신',exact:true}).click();
 await expect(page.getByRole('button',{name:'기상청 자료 갱신',exact:true})).toBeEnabled();
 await explore();
 await page.getByRole('button',{name:'대한민국 전체 지도'}).click();
 await expect(page.locator('.map-statusbar')).toContainText('17개 지역');
 await page.getByLabel('시·도',{exact:true}).selectOption('11');
 await expect(page.locator('.map-statusbar')).toContainText('25개 지역',{timeout:30000});
 await expect(page.locator('.map-data-notice')).toContainText('경계 탐색');
 await page.getByLabel('데이터 모드',{exact:true}).selectOption('sample');
 await expect(page.locator('.map-statusbar')).toContainText('206개 지역');
 await expect(page.locator('.sample-map-banner')).toContainText('합성 데이터');
 await page.locator('.ranking-list button').first().click();
 await expect(page.locator('.score-visual strong')).toHaveText('100.0');
 await selectAnalysisTab(page,'현재기상');
 await expect(page.locator('.regional-weather')).toHaveCount(0);
 await expect(page.locator('.data-board')).toContainText('실제 공공데이터 모드');
 await explore();
 for(const name of ['폭염 강도 HAZARD','인구 노출 EXPOSURE','사회적 취약성 VULNERABILITY']) {
  await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('.map-title-card h2')).toContainText(name.split(' ')[0]);
 }
 await page.locator('.app-header').getByRole('button',{name:'데이터 안내'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByLabel('데이터 모드',{exact:true}).selectOption('sgis');
 await page.route('**/api/view?**',async route=>{if(new URL(route.request().url()).searchParams.get('mode')==='sgis')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'검증용 연결 장애'})});else await route.continue();});
 await page.reload();await expect(page.locator('.map-error-card')).toContainText('불러오지');
 await page.getByRole('button',{name:'테스트용 Sample로 기능 확인'}).click();
 await expect(page.locator('.map-statusbar')).toContainText('206개 지역');
 await expect(page.getByLabel('데이터 모드',{exact:true})).toHaveValue('sample');
 expect(errors).toEqual([]);
 console.log('PASS: flood history, scenario maps, neighborhood search, cleaned metadata, automatic district/dong labels and boundaries, stable ranking across zoom, daily temperature extremes and missing data, automatic report download, current weather, shelter eligibility/schedule filters, scoped facility roundtrip, previous analysis/facility/sample/fallback scenarios. 22 screenshots.');
} catch(e){await page.screenshot({path:path.join(root,'var/e2e-failure.png'),fullPage:true});fs.writeFileSync(path.join(root,'var/e2e-failure.txt'),await page.locator('body').innerText());throw e;}finally{await browser.close();}
