import {chooseNavigation} from './navigation.mjs';
import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const output=path.resolve(import.meta.dirname,'../../var/map-shell');
fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.url());});
await page.route('https://tile.openstreetmap.org/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGP4DwQACfsD/fteaysAAAAASUVORK5CYII=','base64')}));
const choose=name=>chooseNavigation(page,name);
const shot=async name=>{await page.waitForTimeout(400);await page.screenshot({path:path.join(output,name+'.png')});};
try{
 await page.goto(process.env.APP_URL||'http://127.0.0.1:3019');
 await expect(page.locator('.map-statusbar')).toContainText('173개 종합점수',{timeout:30000});
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-ready','true');
 const instance=await page.locator('.map-canvas').getAttribute('data-map-instance');
 const canvas=await page.locator('.map-canvas').boundingBox();
 expect(canvas).toEqual({x:0,y:0,width:1440,height:1000});
 await shot('01-heat-overview');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).fill('부곡4동');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).press('Enter');
 await expect(page.locator('.score-visual strong')).toHaveText('100.0');
 await page.waitForTimeout(800);
 const camera=await page.locator('main').getAttribute('data-camera');
 for(const [name,id] of [['침수','flood'],['산사태','landslide'],['태풍','typhoon'],['한파','cold'],['폭염','heat']]){
   await choose(name);
   await expect(page.locator('main')).toHaveAttribute('data-region','21110600');
   await expect(page.locator('.map-canvas')).toHaveAttribute('data-map-instance',instance);
   await expect(page.locator('.maplibregl-canvas')).toHaveCount(1);
   await page.waitForTimeout(700);
   expect(await page.locator('main').getAttribute('data-camera')).toBe(camera);
   if(['landslide','typhoon','cold'].includes(id)){
     await expect(page.locator('.map-canvas')).toHaveAttribute('data-layer',id);
     await expect(page.locator('.disaster-panel')).toHaveAttribute('data-kind',id);
     if(id==='landslide')await expect(page.locator('.map-timeline')).toHaveCount(0);
     else await expect(page.locator('.map-timeline input[type=range]')).toBeEnabled();
     await expect(page.locator('.disaster-empty')).toHaveCount(0);
     await shot('02-'+id+'-connected');
   }
 }
 await choose('태풍');
 await expect(page.getByLabel('태풍 선택',{exact:true})).toHaveValue('2022-11');
 const track=await(await page.request.get(new URL('/api/typhoons/2022-11?region=21110600',page.url()).href)).json();
 const trackRequests=requests.filter(u=>u.includes('/typhoons/')).length;
 await choose('최근접 시각 보기');
 await expect(page.locator('.timeline-heading time')).toHaveAttribute('datetime',track.closest.timestamp);
 await expect(page.locator('.typhoon-closest')).toContainText(track.closest.distance_km.toFixed(1));
 await choose('이전 시각');await choose('재생');
 await expect(page.locator('.timeline-heading time')).toHaveAttribute('datetime',track.closest.timestamp,{timeout:3000});
 await choose('일시정지');
 expect(requests.filter(u=>u.includes('/typhoons/')).length).toBe(trackRequests);
 await choose('전체 태풍 경로 보기');await page.waitForTimeout(800);
 const wide=JSON.parse(await page.locator('main').getAttribute('data-camera'));
 expect(wide.zoom).toBeLessThan(5);
 await shot('02-typhoon-full-track');
 await choose('선택 지역으로 돌아가기');await page.waitForTimeout(800);
 expect(JSON.parse(await page.locator('main').getAttribute('data-camera')).zoom).toBeGreaterThan(11);
 const typhoonList=await(await page.request.get(new URL('/api/typhoons?region=21110600',page.url()).href)).json();
 const nearest2025=typhoonList.storms.find(s=>s.year===2025).id;
 await page.getByLabel('태풍 연도',{exact:true}).selectOption('2025');
 await expect(page.getByLabel('태풍 선택',{exact:true})).toHaveValue(nearest2025);
 await expect(page.locator('.disaster-panel')).toContainText('2025년');
 await choose('한파');
 await expect(page.getByLabel('겨울 관측 날짜')).toHaveValue('2025-12-01');
 const winter=await(await page.request.get(new URL('/api/climate/seasons/winter-2025-2026?region=21110600',page.url()).href)).json();
 const winterRequests=requests.filter(u=>u.includes('/climate/seasons/')).length;
 await page.getByLabel('겨울 관측 날짜').fill('2026-01-01');
 for(const station of winter.stations){
   const value=station.daily.find(d=>d.date==='2026-01-01').minimum;
   await expect(page.getByRole('button',{name:`${station.station_name} 겨울 관측소 선택`,exact:true})).toContainText(value==null?'관측 없음':`${value.toFixed(1)}℃`);
 }
 await choose('태풍');await expect(page.getByLabel('태풍 선택',{exact:true})).toHaveValue(nearest2025);
 await choose('한파');await expect(page.getByLabel('겨울 관측 날짜')).toHaveValue('2026-01-01');
 await page.getByLabel('겨울 관측 날짜').fill('2026-02-27');await choose('재생');
 await expect(page.getByLabel('겨울 관측 날짜')).toHaveValue('2026-02-28',{timeout:3000});
 await expect(page.getByRole('button',{name:'재생',exact:true})).toContainText('다시 재생');
 expect(requests.filter(u=>u.includes('/climate/seasons/')).length).toBe(winterRequests);
 await choose('침수');await page.getByLabel('침수 구·군',{exact:true}).selectOption('21');
 await choose('산사태');
 await expect(page.locator('.landslide-list>button')).toHaveCount(358);
 await page.locator('.landslide-list>button').first().click();
 await expect(page.locator('.landslide-detail')).toContainText('2014-11-17');
 const landslideId=await page.locator('.landslide-detail').getAttribute('data-id');
 await choose('한파');await choose('산사태');
 await expect(page.locator('.landslide-detail')).toHaveAttribute('data-id',landslideId);
 await page.locator('.landslide-detail summary').click();
 await expect(page.locator('.landslide-detail .neighborhood-profile')).toContainText('반경 300m/500m 통계가 아님');
 await shot('02-landslide-profile');
 await choose('폭염');
 await choose('기상 비교');
 await expect(page.locator('.map-timeline input[type=range]')).toBeEnabled();
 await expect(page.locator('.weather-marker')).not.toHaveCount(0);
 const fetched=requests.filter(u=>u.includes('/current-weather/comparison')).length;
 await choose('이전 날짜');
 const date=await page.locator('.timeline-heading time').getAttribute('datetime');
 const snapshot=await(await page.request.get(new URL('/api/current-weather/comparison',page.url()).href)).json();
 for(const station of snapshot.stations.filter(s=>s.location&&s.location.start_date<=date&&(!s.location.end_date||s.location.end_date>=date))){
   const value=station.recent.daily.find(d=>d.date===date)?.maximum;
   await expect(page.getByRole('button',{name:`${station.station_name} 관측소 선택`,exact:true})).toContainText(value==null?'관측 없음':`${value.toFixed(1)}℃`);
 }
 expect(requests.filter(u=>u.includes('/current-weather/comparison')).length).toBe(fetched);
 await choose('이전 날짜');await choose('재생');
 await expect(page.locator('.timeline-heading time')).toHaveAttribute('datetime',date,{timeout:3000});
 await choose('일시정지');
 await page.waitForTimeout(1100);
 await expect(page.locator('.timeline-heading time')).toHaveAttribute('datetime',date);
 await choose('재생');
 await expect(page.getByRole('button',{name:'재생',exact:true})).toContainText('다시 재생',{timeout:3000});
 await expect(page.getByRole('button',{name:'다음 날짜',exact:true})).toBeDisabled();
 await choose('이전 날짜');
 await shot('03-weather-timeline');
 await choose('태풍');await choose('폭염');
 await expect(page.locator('.timeline-heading time')).toHaveAttribute('datetime',date);
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-map-instance',instance);
 await choose('침수');
 await page.getByLabel('침수 구·군',{exact:true}).selectOption('21');
 await expect(page.locator('.flood-count strong')).toHaveText('186건');
 await page.locator('.flood-record-list>button').first().click();
 await expect(page.locator('.flood-record-detail')).toContainText('2020.07.22');
 await page.getByRole('tab',{name:'침수 예상도',exact:true}).click();
 await choose('118.5mm/h 100년 빈도');
 await expect(page.locator('.updating-pill')).toHaveCount(0);
 await shot('04-flood-forecast');
 await choose('산사태');await choose('침수');
 await expect(page.getByRole('tab',{name:'침수 예상도',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.locator('.map-title-card')).toContainText('118.5');
 // A new region selected while data is unavailable remains selected in both real layers.
 await choose('한파');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).fill('우1동');
 await page.getByRole('combobox',{name:'동네 이름 검색'}).press('Enter');
 const shared=await page.locator('main').getAttribute('data-region');
 await choose('침수');await expect(page.getByLabel('침수 읍·면·동',{exact:true})).toHaveValue(shared);
 await choose('폭염');await choose('동네 분석');
 await expect(page.locator('.selected-region')).toContainText('우1동');
 await choose('현재 시설');
 await page.getByLabel('시설 구·군',{exact:true}).selectOption('21090');
 await expect(page.locator('.facility-list>button')).not.toHaveCount(0);
 await page.locator('.facility-list>button').first().click();await page.waitForTimeout(800);
 const facilityCamera=await page.locator('main').getAttribute('data-camera');
 const facilityText=await page.locator('.facility-detail').innerText();
 await choose('한파');await choose('폭염');await page.waitForTimeout(700);
 expect(await page.locator('main').getAttribute('data-camera')).toBe(facilityCamera);
 await expect(page.locator('.facility-detail')).toHaveText(facilityText,{useInnerText:true});
 await choose('침수');
 for(const width of [768,375]){
   await page.setViewportSize({width,height:900});
   await shot(`05-flood-${width}`);
   expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
   await choose('태풍');await shot(`06-typhoon-${width}`);
   await expect(page.locator('.disaster-panel')).toBeVisible();
   expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
   await choose('침수');
 }
 await page.route('**/api/typhoons/**',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'데이터 준비 중 · 해당 재해의 공식 수집 자료가 아직 연결되지 않았습니다.'})}));
 await page.reload();await choose('태풍');
 await expect(page.locator('.disaster-panel')).toContainText('데이터 준비 중');
 await expect(page.locator('.map-timeline input[type=range]')).toBeDisabled();
 await expect(page.locator('.typhoon-position')).toHaveCount(0);
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-layer','unavailable');
 expect(errors).toEqual([]);
 console.log('PASS: persistent map/camera/region, official landslide/typhoon/winter data, closest approach, full track, cached playback, honest empty states, flood persistence and responsive shell.');
}catch(e){await shot('failure');fs.writeFileSync(path.join(output,'failure.txt'),await page.locator('body').innerText());throw e;}finally{await browser.close();}
