import {chooseNavigation} from './navigation.mjs';
import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve(import.meta.dirname,'../../var/readiness');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
if(!process.env.REAL_TILES)await page.route('https://tile.openstreetmap.org/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGP4DwQACfsD/fteaysAAAAASUVORK5CYII=','base64')}));
const click=name=>chooseNavigation(page,name);
const screenshot=async name=>{await page.waitForTimeout(500);await page.screenshot({path:path.join(out,name+'.png')});};
const list=()=>page.getByRole('button',{name:/^점검 목록 \d+곳$/}).click();
try {
 await page.goto(process.env.APP_URL||'http://127.0.0.1:3019');await page.getByRole('button',{name:'건너뛰기',exact:true}).click();
 await expect(page.locator('.map-statusbar')).toContainText('173개 종합점수',{timeout:30000});
 await expect(page.locator('.readiness-finder')).toBeVisible();
 await expect(page.locator('.basemap-toggle')).toHaveCount(0);
 await expect(page.locator('.map-attribution')).toContainText('OpenStreetMap');
 await expect(page.locator('.map-canvas')).toHaveAttribute('data-ready','true');
 await screenshot('01-find-neighborhood');
 const view=await(await page.request.get(new URL('/api/view?parent_code=21&mode=sgis&layer=risk&level=dong',page.url()).href)).json();
 // Assertions use source statistics and original score values, never synthesized hazard records.
 const eligible=view.regions.filter(r=>['elderly_ratio','old_house_ratio'].every(k=>r.factors.some(f=>f.key===k&&f.value!=null&&f.comparison_average!=null&&f.value>f.comparison_average)));
 const expected=eligible.sort((a,b)=>(b.risk_score??-1)-(a.risk_score??-1));
 await page.locator('.readiness-criteria button').filter({hasText:'고령인구'}).click();
 await page.locator('.readiness-criteria button').filter({hasText:'노후주택'}).click();
 await click('조건에 맞는 동네 찾기');
 await expect(page.locator('.readiness-results-summary strong')).toHaveText(`${expected.length}곳`);
 await expect(page.locator('.readiness-results article').first()).toHaveAttribute('data-region',expected[0].region_code);
 await expect(page.locator('.readiness-results article').first().locator('.result-score')).toContainText(expected[0].risk_score.toFixed(1));
 await expect(page.locator('.legend-candidates')).toContainText(`${expected.length}곳`);
 await screenshot('02-matching-neighborhoods');
 await page.locator('.readiness-results article').first().getByRole('button',{name:/점검 목록에 담기/}).click();
 await expect(page.getByRole('button',{name:'점검 목록 1곳'})).toBeVisible();
 await expect(page.locator('.readiness-results article').first().getByRole('button',{name:/점검 목록에 담기/})).toBeDisabled();
 await page.locator('.readiness-results article').first().getByRole('button',{name:'근거·대응 확인'}).click();
 await expect(page.locator('.selected-region')).toContainText(expected[0].region_name);
 await expect(page.locator('.review-panel')).toBeVisible();
 await expect(page.locator('.inspection-savebar>button').first()).toBeDisabled();
 await click('이 동의 현재 시설 확인');
 await expect(page.locator('.facility-list>button')).not.toHaveCount(0);
 await page.locator('.facility-list>button').first().click();
 await expect(page.locator('.facility-detail')).toBeVisible();
 const facilityName=await page.locator('.inspection-savebar small').innerText();
 await page.locator('.inspection-savebar>button').first().click();
 await list();await expect(page.locator('.inspection-cards article')).toHaveCount(2);
 await screenshot('03-inspection-list');
 const facilityCard=page.locator('.inspection-cards article').first();
 await facilityCard.getByRole('checkbox').check();
 await facilityCard.getByRole('textbox').fill('방문 전 등록 운영시간과 이용대상 확인');
 const download=page.waitForEvent('download');await click('내려받기');await (await download).saveAs(path.join(out,'inspection.md'));
 const exported=fs.readFileSync(path.join(out,'inspection.md'),'utf8');
 expect(exported).toContain(`## [x] ${facilityName}`);expect(exported).toContain('방문 전 등록 운영시간과 이용대상 확인');expect(exported).toContain(expected[0].region_name);
 await page.reload();await list();await expect(page.locator('.inspection-cards article')).toHaveCount(2);
 await expect(page.locator('.inspection-cards article').first().getByRole('checkbox')).toBeChecked();
 await page.locator('.inspection-cards article').first().getByRole('button',{name:'지도에서 다시 보기'}).click();
 await expect(page.locator('.facility-detail')).toContainText(facilityName);
 await expect(page.locator('.inspection-savebar>button').first()).toBeDisabled();
 await list();await page.locator('.inspection-cards article').last().getByRole('button',{name:'지도에서 다시 보기'}).click();
 await expect(page.locator('main')).toHaveAttribute('data-region',expected[0].region_code);
 await expect(page.locator('.score-visual strong')).toHaveText(expected[0].risk_score.toFixed(1));
 await click('침수');await page.getByLabel('침수 구·군',{exact:true}).selectOption('21');
 await expect(page.locator('.flood-record-list>button')).not.toHaveCount(0);await page.locator('.flood-record-list>button').first().click();
 const floodName=await page.locator('.inspection-savebar small').innerText();await page.locator('.inspection-savebar>button').first().click();
 await list();await page.locator('.inspection-cards article').first().getByRole('button',{name:'지도에서 다시 보기'}).click();
 await expect(page.locator('.flood-record-detail')).toContainText(floodName);
 await click('산사태');await click('침수');await page.getByLabel('침수 구·군',{exact:true}).selectOption('21');await click('산사태');
 await expect(page.locator('.landslide-list>button')).not.toHaveCount(0);await page.locator('.landslide-list>button').first().click();
 const pointName=await page.locator('.inspection-savebar small').innerText();await page.locator('.inspection-savebar>button').first().click();
 await list();await expect(page.locator('.inspection-cards article')).toHaveCount(4);
 await page.locator('.inspection-cards article').first().getByRole('button',{name:'지도에서 다시 보기'}).click();
 await expect(page.locator('.landslide-detail')).toContainText(pointName);
 await list();await page.locator('.inspection-cards article').first().getByRole('button',{name:/목록에서 빼기/}).click();await expect(page.locator('.inspection-cards article')).toHaveCount(3);
 await click('동네 찾기');await page.getByLabel('동네 찾기 시·군·구').selectOption('21010');
 await expect(page.locator('.readiness-submit')).toContainText('중구 분석');
 for(const button of await page.locator('.readiness-criteria button[aria-pressed=true]').all())await button.click();
 await click('조건에 맞는 동네 찾기');
 const districtView=await(await page.request.get(new URL('/api/view?parent_code=21010&mode=sgis&layer=risk&level=children',page.url()).href)).json();
 const districtFirst=districtView.regions.filter(r=>r.risk_score!=null).sort((a,b)=>b.risk_score-a.risk_score)[0];
 await page.locator('.readiness-results article').first().getByRole('button',{name:/점검 목록에 담기/}).click();
 await page.getByLabel('데이터 모드',{exact:true}).selectOption('sample');
 await list();await page.locator('.inspection-cards article').first().getByRole('button',{name:'지도에서 다시 보기'}).click();
 await expect(page.getByLabel('데이터 모드',{exact:true})).toHaveValue('sgis');
 await expect(page.locator('.selected-region')).toContainText(districtFirst.region_name);
 await expect(page.locator('.score-visual strong')).toHaveText(districtFirst.risk_score.toFixed(1));
 await expect(page.locator('.score-card>p').last()).toContainText(districtFirst.comparison_region);
 await click('동네 찾기');await click('조건 수정');await page.getByLabel('동네 찾기 시·도').selectOption('11');
 await expect(page.locator('.readiness-submit')).toContainText('이 지역의 분석자료는 준비 중');
 await expect(page.getByRole('button',{name:'조건에 맞는 동네 찾기'})).toBeDisabled();
 await page.getByLabel('동네 찾기 시·도').selectOption('21');
 for(const width of [1024,768,375]){
   await page.setViewportSize({width,height:900});await screenshot(`04-find-${width}`);
   expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
   await expect(page.getByRole('button',{name:'동네 찾기',exact:true})).toBeInViewport();
   await expect(page.getByRole('button',{name:'조건에 맞는 동네 찾기',exact:true})).toBeInViewport();
   await list();await screenshot(`05-list-${width}`);await click('동네 찾기');
 }
 expect(errors).toEqual([]);
 console.log('PASS: real indicator filtering, unchanged scores, review/facility links, region/facility/flood/landslide saving and reopening, duplicate prevention, notes/completion/export/persistence/removal, unsupported-region state, responsive UI.');
}catch(e){await screenshot('failure');fs.writeFileSync(path.join(out,'failure.txt'),await page.locator('body').innerText());throw e;}finally{await browser.close();}
